name: First workflow

on: push 

jobs: 
  build:
    run-ons: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a sample github actions
        run: echo "This workflow runs succefully for this particular actions"
