name: linting-python-code

on:
 workflow_dispatch:
 push:
  branches:
   - master
   - main
 pull_request:
  branches:
   - master 
   - main

jobs:
 python-linting-code:
  runs-on: ubuntu-latest
 
  steps:
   - name: Super-Linter
     uses: super-linter/super-linter@v5.7.2
            
   
